### ISSUE TITLE
can't resolve script with webpack

### ISSUE THREAD

**Issue by CHBaker** [mmacaula/cesium-webpack#6]
Following steps for the using-pre-built. Initial set up failed,

ran 
```
$ node_modules/.bin/webpack
module.js:487
    throw err;
    ^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hawtballa/Desktop/cesium-webpack/using-pre-built/webpack.config.js:1:80)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

so I ran ```npm install hatml-webpack-plugin --save```

then I ran ```node_modules/.bin/webpack``` again and got this error:
```
$ node_modules/.bin/webpack
Hash: bb7af38dc399edb52a4d
Version: webpack 3.6.0
Time: 308ms
     Asset      Size  Chunks             Chunk Names
 bundle.js   2.96 kB       0  [emitted]  main
index.html  52 bytes          [emitted]
   [0] ./app.js 201 bytes {0} [built]

ERROR in ./app.js
Module not found: Error: Can't resolve 'script' in '/home/hawtballa/Desktop/cesium-webpack/using-pre-built'
 @ ./app.js 2:0-43

ERROR in ./app.js
Module not found: Error: Can't resolve 'style' in '/home/hawtballa/Desktop/cesium-webpack/using-pre-built'
 @ ./app.js 3:0-43

ERROR in Path must be a string. Received undefined

```

**Comment by mmacaula** [comment]
This project is deprecated, see the updated Readme for more up to date instructions
